import enum
import uuid
from datetime import datetime

from sqlalchemy import DateTime, Enum, Float, ForeignKey, Integer, String, Boolean
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base


class MachineStatus(str, enum.Enum):
    online = "online"
    offline = "offline"


class Role(str, enum.Enum):
    """Layer 6 — Role based access per machine."""
    owner = "owner"
    admin = "admin"
    member = "member"
    viewer = "viewer"


class Machine(Base):
    __tablename__ = "machines"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    owner_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)

    name: Mapped[str] = mapped_column(String(120), nullable=False)

    # Public machine identifier the agent presents (safe to log / display).
    machine_uid: Mapped[str] = mapped_column(String(64), unique=True, index=True)

    # NOTE: for a real deployment encrypt this at rest (KMS / envelope
    # encryption) rather than storing plaintext — it's kept simple here so
    # the HMAC verification code stays readable.
    secret: Mapped[str] = mapped_column(String(128), nullable=False)

    paired: Mapped[bool] = mapped_column(Boolean, default=False)

    status: Mapped[MachineStatus] = mapped_column(Enum(MachineStatus), default=MachineStatus.offline)
    last_seen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    os: Mapped[str | None] = mapped_column(String(64), nullable=True)
    cpu_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    ram_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    disk_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Reported on every periodic status message (same cadence as
    # cpu/ram/disk) rather than only on-demand — lets the dashboard alert
    # proactively ("idle 30 min") instead of requiring someone to click a
    # button to notice nobody's at the keyboard.
    idle_seconds: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ip_address: Mapped[str | None] = mapped_column(String(64), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)

    owner = relationship("User", back_populates="machines")

    commands = relationship(
        "Command",
        back_populates="machine",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    access_grants = relationship(
        "MachineAccess",
        back_populates="machine",
        cascade="all, delete-orphan",
    )
    
    commands = relationship("Command", back_populates="machine", cascade="all, delete-orphan")


class MachineAccess(Base):
    """Grants a non-owner user a role on a specific machine."""
    __tablename__ = "machine_access"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    machine_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("machines.id"), nullable=False)
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
    role: Mapped[Role] = mapped_column(Enum(Role), default=Role.viewer)

    machine = relationship("Machine", back_populates="access_grants")


class PairingCode(Base):
    """Layer 4 — Device pairing. Generated by the website, entered on the agent."""
    __tablename__ = "pairing_codes"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    code: Mapped[str] = mapped_column(String(16), unique=True, index=True)
    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id"), nullable=False)
    machine_name: Mapped[str] = mapped_column(String(120))
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    used: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow)
